### ISSUE TITLE
AWS Template is broken

### ISSUE THREAD

**Issue by tux2603** [RLey/wsu-tunnel-app#11]
AWS-Ubuntu.json on the AWS branch is broken. It does not create an functional instance.

**Comment by mkijowski** [comment]
Seems to be related to this error while creating from CF template: Exactly one of [NatGatewayId, NetworkInterfaceId, InstanceId, VpcPeeringConnectionId, EgressOnlyInternetGatewayId, GatewayId] must be specified and not empty.

Cannot create Route.  Json route info:
```
"Route": {
147             "Type": "AWS::EC2::Route",
148             "DependsOn": "AttachGateway",
149             "Properties": {
150                 "RouteTableId": {
151                     "Ref": "RouteTable"
152                 },
153                 "DestinationCidrBlock": "0.0.0.0/0"
154             }
155         },
```
And in the yml file:
```
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
GatewayId: !Ref InternetGateway
```
